### ISSUE TITLE
Symbols triggering Apple's Private API rejection

### ISSUE THREAD

**Issue by auibrian** [VerveWireless/verve-ios-adsdk#4]
The symbols `realDelegate` and `sessionStarted` are causing some apps to be rejected by Apple for use of Private API (section 2.51). Is there any way for the next release to change these symbol names? I've had to remove the SDK for my client in order to make it through app store submission.

**Comment by auibrian** [comment]
I've just checked 3.1.0: it seems it only has `realDelegate` and not `sessionStarted`. So only one change would be required.

**Comment by christinalong** [comment]
@auibrian - Thanks for opening the issue. This was brought to our attention yesterday and after some deeper investigation, we learned that two of the third party SDKs which we have included had these private APIs. The issue has been resolved in the latest version (v3.2.1) of our SDK which is currently with our QA team for testing. Once it has cleared QA, we will release to Github. 

It seems it varies from reviewer to reviewer whether they check for these specific APIs. All of our own applications with the SDK included pass the Xcode Validate stage and are able to be submitted/approved in the store without any issue. This is why we hadn't caught this during our own testing. 

Thanks again for the information!

**Comment by auibrian** [comment]
Agreed, the Xcode validate doesn't seem to catch this. It feels like the reviewers are running `otool` themselves and I guess it is up to the reviewer whether they let it through!

Thanks for addressing this so quickly, we'll be watching for v3.2.1!

**Comment by christinalong** [comment]
@auibrian - The new version v3.2.1 is available. Let us know if you have any additional issues!
