### ISSUE TITLE
iTunes Submission Issue

### ISSUE THREAD

**Issue by abhimarch28** [VerveWireless/verve-ios-adsdk#5]
Hello,

While using the Verve SDK I was initially having below crash at the time of app start

dyld: Library not loaded: @rpath/VerveAd.framework/VerveAd
  Referenced from: /var/containers/Bundle/Application/104D9F0C-DBEE-4ABD-9D20-311D4EACA4D8/(appname).app/(appname)
  Reason: image not found

Adding the framework to the Embedded Binary Libraries solved this crash, but this made an issue with the iTunes submission. Please find the attachment for the same.

Please suggest a solution as I have an urgent upload of my app.

<img width="828" alt="screen_shot_2016-09-19_at_9 41 53_pm" src="https://cloud.githubusercontent.com/assets/22313862/18659601/55f91ace-7f29-11e6-940e-10ca17f5d1a5.png">

**Comment by christinalong** [comment]
@abhimarch28 - Please make sure that you have completed step 3.4 in the Getting Started Guide. This step is required to avoid the app store submission error that you are seeing.

<img width="766" alt="screen shot 2016-09-20 at 8 52 40 am" src="https://cloud.githubusercontent.com/assets/5808791/18670827/a78eebe4-7f0f-11e6-902e-3a13b4d340c8.png">
